# Generated by Django 5.0 (migration created manually)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='procurements.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stop_at_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Stop accepting when this amount is reached', max_digits=12, null=True)),
                ('unit', models.CharField(default='units', help_text='e.g., kg, pieces, liters', max_length=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('stopped', 'Stopped'), ('payment', 'Payment in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='procurements.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_procurements', to='users.user')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_procurements', to='users.user')),
            ],
            options={
                'db_table': 'procurements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='procurements.procurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.user')),
            ],
            options={
                'db_table': 'participants',
                'unique_together': {('procurement', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['status'], name='procurement_status_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['organizer'], name='procurement_organiz_d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['category'], name='procurement_categor_g7h8i9_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['city'], name='procurement_city_j0k1l2_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['deadline'], name='procurement_deadlin_m3n4o5_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['created_at'], name='procurement_created_p6q7r8_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['procurement', 'status'], name='participant_procure_s9t0u1_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='participant_user_id_v2w3x4_idx'),
        ),
    ]
