# Generated by Django 5.0 (migration created manually)

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('websocket', 'WebSocket'), ('vk', 'VKontakte')], default='telegram', max_length=20)),
                ('platform_user_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+79991234567'", regex='^\\+?[1-9]\\d{10,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('organizer', 'Organizer'), ('supplier', 'Supplier')], default='buyer', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('language_code', models.CharField(default='ru', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_type', models.CharField(blank=True, max_length=50)),
                ('dialog_state', models.CharField(blank=True, max_length=50)),
                ('dialog_data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['platform', 'platform_user_id'], name='users_platfor_c3e4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_7f85d1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_d5e9f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('platform', 'platform_user_id')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'dialog_type'], name='user_sessio_user_id_1a2b3c_idx'),
        ),
    ]
